In [ ]:
from IPython.core.display import Markdown
from IPython.core.display_functions import display
import pandas as pd
from pathlib import Path

""" métodos de verificación y carga de archivos """
def verificar_archivo(str) -> Path:
    # Archivo de encuesta de inversores
    ruta = Path("./csv/") / str
    
    # Verificar exitencia
    if ruta.exists():
            return ruta
            
    # Devolver error Archivo no encontrado
    raise FileNotFoundError(
        "No se encontró el directorio con los archivos del Proyecto C."
    )

def cargar_datos(archivos):
    dict_datos = {}
    for nombre, nombre_archivo in archivos.items():
        # verificar que cada archivo existe
        ruta = verificar_archivo(nombre_archivo)
        # cargar datos
        dict_datos[nombre] = pd.read_csv(ruta)

    return dict_datos

""" métodos de análisis de datos """
def mostrar_primeras_filas(nombre: str, datos: pd.DataFrame) -> None:
    # 1.1 mostrar las primeras filas 
    display(Markdown(f"### **Archivo: {nombre}.csv**"))
    display(datos.head())

def mostrar_descripcion(datos: pd.DataFrame) -> None:
    # 1.2
    # cantidad de filas y columnas
    filas, columnas = datos.shape
    display(Markdown(f"**Filas y columnas:** {filas} filas, {columnas} columnas"))

    # tipos de dato
    display(Markdown("#### Tipos de dato por columna"))
    display(datos.dtypes.to_frame(name="tipo_dato").T)

    # cantidad de categorías en las variables categóricas
    categoricas = datos.select_dtypes(include=["object", "category", "string", "bool"])
    if not categoricas.empty:
        display(Markdown("#### Cantidad de categorías (variables categóricas)"))
        display(categoricas.nunique().to_frame(name="cantidad_categorias"))

    # descripción estadística de las continuas
    continuas = datos.select_dtypes(include="number")
    if not continuas.empty:
        display(Markdown("#### Descripción estadística (variables continuas)"))
        display(continuas.describe().T)
    return

def mostrar_duplicados(datos: pd.DataFrame) -> None:
    # 1.3 búsqueda de formularios enviados dos veces
    # y operaciones por duplicado (solo se muestran, no se eliminan)
    # duplicados exactos (todas las columnas iguales)
    exactos = datos.duplicated()
    display(Markdown(
        f"#### Duplicados exactos: {exactos.sum()} filas "
    ))
    if exactos.any():
        display(datos[datos.duplicated(keep=False)].sort_values(list(datos.columns)).head(10))

    # formularios enviados dos veces: mismo id_cliente en la encuesta
    if "id_cliente" in datos.columns and "id_movimiento" not in datos.columns:
        repetidos = datos[datos.duplicated(subset="id_cliente", keep=False)]
        display(Markdown(
            f"#### Formularios con id_cliente repetido: "
            f"{datos.duplicated(subset='id_cliente').sum()} filas de más "
            f"({len(repetidos)} filas involucradas)"
        ))
        if not repetidos.empty:
            display(repetidos.sort_values("id_cliente").head(10))

    # operaciones duplicadas: misma operación con distinto id_movimiento
    if "id_movimiento" in datos.columns:
        display(Markdown(
            f"**id_movimiento repetidos:** {datos.duplicated(subset='id_movimiento').sum()}"
        ))
        clave = [c for c in datos.columns if c != "id_movimiento"]
        operaciones = datos[datos.duplicated(subset=clave, keep=False)]
        display(Markdown(
            f"**Operaciones duplicadas (ignorando id_movimiento):** "
            f"{datos.duplicated(subset=clave).sum()} filas de más "
            f"({len(operaciones)} filas involucradas)"
        ))
        if not operaciones.empty:
            display(operaciones.sort_values(clave).head(10))
    return

def mostrar_faltantes(datos: pd.DataFrame) -> None:
    # 1.4 faltantes por columnas (solo valores nulos reales, isna())
    faltantes = datos.isna().sum()
    resumen = pd.DataFrame({
        "faltantes": faltantes
    })
    resumen = resumen[resumen["faltantes"] > 0].sort_values("faltantes", ascending=False)

    display(Markdown("**Faltantes por columna**"))
    if resumen.empty:
        display(Markdown("No hay valores faltantes."))
        return
    display(resumen)

    # filas afectadas, filtradas por columna con faltantes
    for columna in resumen.index:
        filas_afectadas = datos[datos[columna].isna()]
        display(Markdown(
            f"Filas con `{columna}` faltante: **{len(filas_afectadas)}** "
            f"de {len(datos)} (se muestran las primeras 3)"
        ))
        display(filas_afectadas.head(3))
    return

def mostrar_valores_raros(datos: pd.DataFrame) -> None:
    # 1.5 valores raros 
    # valores raros: no coinciden con el tipo de dato de la columna
    # y formas de decir "no contestó"
    textos = datos.select_dtypes(exclude="number").columns
    fechas = [c for c in textos if c.startswith("fecha")]

    # texto en columnas que deberían ser numéricas
    for columna in textos:
        if columna in fechas:
            continue
        valores = datos[columna].dropna().astype(str)
        es_numero = valores.str.fullmatch(r"\s*\$?\s*-?\d+([.,]\d+)*\s*")
        if valores.empty or es_numero.mean() < 0.5:
            continue  # la columna es realmente de texto
        raros = valores[~es_numero]
        display(Markdown(f"`{columna}` es numérica pero tiene **{len(raros)}** valores que no son números"))
        display(raros.value_counts().to_frame(name="cantidad"))

    # fechas que no son válidas
    for columna in fechas:
        valores = datos[columna].dropna().astype(str)
        raros = valores[pd.to_datetime(valores, errors="coerce", format="mixed").isna()]
        if not raros.empty:
            display(Markdown(f"`{columna}` tiene **{len(raros)}** fechas no válidas"))

    # formas de decir "no contestó": isna() solo detecta una
    marcadores = ["prefiero no contestar", "s/d", "n/c", "ns/nc", "no sabe", "no contesta", "-", "?", ""]
    centinelas = [-999, -99, 999, 9999]
    resumen = []
    for columna in datos.columns:
        if columna.startswith("id_"):
            continue
        if columna in textos:
            disfrazados = datos[columna].astype(str).str.strip().str.lower().isin(marcadores)
        else:
            disfrazados = datos[columna].isin(centinelas)
        if disfrazados.any():
            resumen.append((columna, datos[columna].isna().sum(), disfrazados.sum()))

    display(Markdown("**Formas de decir «no contestó»: isna() frente al total real**"))
    if not resumen:
        display(Markdown("No se encontraron marcadores de no respuesta."))
        return
    tabla = pd.DataFrame(
        [(c, n, d) for c, n, d in resumen],
        columns=["columna", "nulos_isna", "disfrazados"],
    ).set_index("columna")
    tabla["total_no_respuesta"] = tabla.sum(axis=1)
    display(tabla)
    return

def mostrar_rangos_imposibles(datos: pd.DataFrame) -> None:
    # 1.5 valores raros y rangos imposibles
    # numéricas fuera de su rango posible (solo se detectan, no se corrigen)
    infinito = float("inf")
    rangos = {
        "edad": (18, 100),
        "patrimonio_invertible_usd": (0, infinito),
        "meses_gastos_cubiertos": (0, infinito),
        "anios_experiencia_invirtiendo": (0, infinito),
        "puntaje_test_conocimiento": (0, 10),
        "conocimiento_autopercibido": (1, 5),
        "monto": (0, infinito),
    }

    display(Markdown("**Numéricas con rangos imposibles**"))
    encontrados = 0
    for columna, (minimo, maximo) in rangos.items():
        if columna not in datos.columns:
            continue
        fuera = datos[columna].notna() & ~datos[columna].between(minimo, maximo)
        if fuera.any():
            encontrados += 1
            display(Markdown(
                f"`{columna}` fuera de [{minimo}, {maximo}]: **{fuera.sum()}** valores "
                f"(desde {datos.loc[fuera, columna].min()} hasta {datos.loc[fuera, columna].max()})"
            ))

    # no se puede invertir más años que los vividos
    if "edad" in datos.columns and "anios_experiencia_invirtiendo" in datos.columns:
        incoherentes = datos["anios_experiencia_invirtiendo"] > datos["edad"]
        if incoherentes.any():
            encontrados += 1
            display(Markdown(f"`anios_experiencia_invirtiendo` mayor que `edad`: **{incoherentes.sum()}** filas"))

    if encontrados == 0:
        display(Markdown("No se encontraron rangos imposibles."))
    return

def mostrar_campos_vacios(datos: pd.DataFrame) -> None:
    # 1.6 campos vacíos
    return

def validar_faltantes(datos: pd.DataFrame) -> None:
    # 1.7 faltantes de ingresos y patrimonios repartidos
    return

def validar_patrimonio(datos: pd.DataFrame) -> None:
    # 1.7 faltantes de ingresos y patrimonios repartidos
    return

def mostrar_datos(dict_datos) -> None:
    # imprimir tipos de datos
    for nombre, datos in dict_datos.items():

        # 1.1 mostrar las primeras filas 
        mostrar_primeras_filas(nombre, datos)

        # 1.2 cantidad de filas y columnas, tipos de datos, 
        # cantidad de categorías y descripción de las continuas
        mostrar_descripcion(datos)

        # 1.3 búsqueda de formularios enviados dos veces
        # y operaciones por duplicado
        mostrar_duplicados(datos)

        # 1.4 faltantes por columnas
        mostrar_faltantes(datos)

        # 1.5 valores raros y rangos imposibles
        mostrar_valores_raros(datos)
        mostrar_rangos_imposibles(datos)

        # 1.6 campos vacíos
        mostrar_campos_vacios(datos)

        # 1.7 faltantes de ingresos y patrimonios repartidos
        validar_faltantes(datos)
        validar_patrimonio(datos) 

    return

""" métodos generales """
def main() -> None:
    # nombre de los archivos
    archivos = {
        "encuesta_inversores": "encuesta_inversores.csv",
        "movimientos_cartera": "movimientos_cartera.csv",
        "catalogo_instrumentos": "catalogo_instrumentos.csv",
        "tasas_referencia": "tasas_referencia.csv",
    }
    # cargar datos
    dict_datos = cargar_datos(archivos)

    # mostrar resultados
    mostrar_datos(dict_datos)

if __name__ == "__main__":
    main()

### **Archivo: encuesta_inversores.csv**

,id_cliente,fecha_respuesta,edad,sexo,departamento,cantidad_dependientes,nivel_educativo,ocupacion,ingreso_mensual_liquido,patrimonio_invertible_usd,...,reaccion_caida_20,objetivo_principal,fuente_informacion,prioridad_plazo_fijo,prioridad_letras_bcu,prioridad_fondos_locales,prioridad_obligaciones,prioridad_etf_exterior,prioridad_inmuebles,prioridad_criptomonedas
0,20504,2026-06-24,52.0,Masculino,Montevideo,0,Terciaria completa,Profesional independiente,141700,4200.0,...,Compraría más,Crecimiento del capital,Amigos y familia,7,6,4,5,1,3,2
1,20466,2026-03-29,62.0,Masculino,Colonia,0,Terciaria completa,Jubilado,$ 131.300,13900.0,...,No haría nada,Generar una renta mensual,Investigación propia,7,6,4,5,2,3,1
2,20432,2026-01-11,40.0,Masculino,Maldonado,0,Terciaria completa,Jubilado,53700,4600.0,...,No haría nada,Complemento jubilatorio,Asesor,7,6,4,3,2,5,1
3,20052,2026-02-21,48.0,Masculino,Canelones,0,Posgrado,Empresario / dueño de negocio,0,27700.0,...,No haría nada,Compra de vivienda,Asesor financiero,7,4,6,5,2,3,1
4,20084,2026-04-01,82.0,Femenino,Canelones,0,Posgrado,Jubilado,85100,12100.0,...,No haría nada,Complemento jubilatorio,Amigos y familia,7,6,3,4,1,5,2

**Filas y columnas:** 657 filas, 31 columnas

#### Tipos de dato por columna

,id_cliente,fecha_respuesta,edad,sexo,departamento,cantidad_dependientes,nivel_educativo,ocupacion,ingreso_mensual_liquido,patrimonio_invertible_usd,...,reaccion_caida_20,objetivo_principal,fuente_informacion,prioridad_plazo_fijo,prioridad_letras_bcu,prioridad_fondos_locales,prioridad_obligaciones,prioridad_etf_exterior,prioridad_inmuebles,prioridad_criptomonedas
tipo_dato,int64,str,float64,str,str,int64,str,str,str,float64,...,str,str,str,int64,int64,int64,int64,int64,int64,int64

#### Cantidad de categorías (variables categóricas)

                           cantidad_categorias
fecha_respuesta                            258
sexo                                         2
departamento                                25
nivel_educativo                              4
ocupacion                                    6
ingreso_mensual_liquido                    537
tiene_deudas                                 2
tiene_fondo_emergencia                       4
perfil_autodeclarado                         6
tolerancia_perdida_maxima                    5
horizonte_inversion                          7
frecuencia_monitoreo                         8
retorno_esperado_anual                       5
reaccion_caida_20                            4
objetivo_principal                           6
fuente_informacion                           9

#### Descripción estadística (variables continuas)

,count,mean,std,min,25%,50%,75%,max
id_cliente,657.0,20319.485540,184.946342,20001.0,20158.0,20320.0,20479.0,20640.0
edad,651.0,46.643625,14.059069,0.0,38.0,46.0,53.5,154.0
cantidad_dependientes,657.0,0.907154,0.955836,0.0,0.0,1.0,1.0,5.0
patrimonio_invertible_usd,628.0,24964.990446,29705.021949,-999.0,7400.0,15900.0,31650.0,279100.0
meses_gastos_cubiertos,624.0,2.931090,3.927930,0.0,0.0,0.0,6.0,12.0
anios_experiencia_invirtiendo,657.0,5.382040,4.701308,0.0,2.0,4.0,7.0,34.0
puntaje_test_conocimiento,657.0,4.298326,2.063596,-1.0,3.0,4.0,6.0,10.0
conocimiento_autopercibido,657.0,2.563166,0.998191,1.0,2.0,3.0,3.0,5.0
prioridad_plazo_fijo,657.0,6.347032,0.944235,2.0,6.0,7.0,7.0,7.0
prioridad_letras_bcu,657.0,5.948250,1.027251,1.0,6.0,6.0,7.0,7.0
prioridad_fondos_locales,657.0,4.185693,1.200448,1.0,3.0,4.0,5.0,7.0
prioridad_obligaciones,657.0,3.625571,1.131513,1.0,3.0,3.0,4.0,7.0
prioridad_etf_exterior,657.0,2.213090,0.919112,1.0,2.0,2.0,2.0,7.0
prioridad_inmuebles,657.0,4.482496,1.214777,1.0,4.0,5.0,5.0,7.0
prioridad_criptomonedas,657.0,1.197869,0.515428,1.0,1.0,1.0,1.0,5.0

#### Duplicados exactos: 17 filas

,id_cliente,fecha_respuesta,edad,sexo,departamento,cantidad_dependientes,nivel_educativo,ocupacion,ingreso_mensual_liquido,patrimonio_invertible_usd,...,reaccion_caida_20,objetivo_principal,fuente_informacion,prioridad_plazo_fijo,prioridad_letras_bcu,prioridad_fondos_locales,prioridad_obligaciones,prioridad_etf_exterior,prioridad_inmuebles,prioridad_criptomonedas
12,20024,2026-02-07,53.0,Masculino,Maldonado,0,Terciaria incompleta,Empleado en relación de dependencia,"22.200,00",3500.0,...,Vendería una parte,Complemento jubilatorio,Redes sociales,7,6,5,4,2,3,1
447,20024,2026-02-07,53.0,Masculino,Maldonado,0,Terciaria incompleta,Empleado en relación de dependencia,"22.200,00",3500.0,...,Vendería una parte,Complemento jubilatorio,Redes sociales,7,6,5,4,2,3,1
59,20063,2026-02-01,51.0,Masculino,Río Negro,0,Terciaria completa,Empleado público,$ 90.100,5800.0,...,No haría nada,Crecimiento del capital,Redes sociales,4,6,7,2,3,5,1
239,20063,2026-02-01,51.0,Masculino,Río Negro,0,Terciaria completa,Empleado público,$ 90.100,5800.0,...,No haría nada,Crecimiento del capital,Redes sociales,4,6,7,2,3,5,1
31,20077,12/06/2026,52.0,Masculino,Maldonado,0,Terciaria completa,Empleado en relación de dependencia,"106.600,00",14500.0,...,No haría nada,Complemento jubilatorio,Prensa especializada,5,7,2,6,3,4,1
647,20077,12/06/2026,52.0,Masculino,Maldonado,0,Terciaria completa,Empleado en relación de dependencia,"106.600,00",14500.0,...,No haría nada,Complemento jubilatorio,Prensa especializada,5,7,2,6,3,4,1
106,20093,2026-03-31,53.0,Masculino,Colonia,1,Terciaria completa,Empleado en relación de dependencia,"89.200,00",58100.0,...,No haría nada,Generar una renta mensual,Prensa especializada,7,5,4,6,1,3,2
143,20093,2026-03-31,53.0,Masculino,Colonia,1,Terciaria completa,Empleado en relación de dependencia,"89.200,00",58100.0,...,No haría nada,Generar una renta mensual,Prensa especializada,7,5,4,6,1,3,2
8,20125,03/05/2026,53.0,Femenino,Canelones,0,Terciaria completa,Empleado en relación de dependencia,62600.00,10200.0,...,No haría nada,Generar una renta mensual,Redes sociales,6,7,4,3,2,5,1
252,20125,03/05/2026,53.0,Femenino,Canelones,0,Terciaria completa,Empleado en relación de dependencia,62600.00,10200.0,...,No haría nada,Generar una renta mensual,Redes sociales,6,7,4,3,2,5,1

#### Formularios con id_cliente repetido: 17 filas de más (34 filas involucradas)

,id_cliente,fecha_respuesta,edad,sexo,departamento,cantidad_dependientes,nivel_educativo,ocupacion,ingreso_mensual_liquido,patrimonio_invertible_usd,...,reaccion_caida_20,objetivo_principal,fuente_informacion,prioridad_plazo_fijo,prioridad_letras_bcu,prioridad_fondos_locales,prioridad_obligaciones,prioridad_etf_exterior,prioridad_inmuebles,prioridad_criptomonedas
12,20024,2026-02-07,53.0,Masculino,Maldonado,0,Terciaria incompleta,Empleado en relación de dependencia,"22.200,00",3500.0,...,Vendería una parte,Complemento jubilatorio,Redes sociales,7,6,5,4,2,3,1
447,20024,2026-02-07,53.0,Masculino,Maldonado,0,Terciaria incompleta,Empleado en relación de dependencia,"22.200,00",3500.0,...,Vendería una parte,Complemento jubilatorio,Redes sociales,7,6,5,4,2,3,1
239,20063,2026-02-01,51.0,Masculino,Río Negro,0,Terciaria completa,Empleado público,$ 90.100,5800.0,...,No haría nada,Crecimiento del capital,Redes sociales,4,6,7,2,3,5,1
59,20063,2026-02-01,51.0,Masculino,Río Negro,0,Terciaria completa,Empleado público,$ 90.100,5800.0,...,No haría nada,Crecimiento del capital,Redes sociales,4,6,7,2,3,5,1
31,20077,12/06/2026,52.0,Masculino,Maldonado,0,Terciaria completa,Empleado en relación de dependencia,"106.600,00",14500.0,...,No haría nada,Complemento jubilatorio,Prensa especializada,5,7,2,6,3,4,1
647,20077,12/06/2026,52.0,Masculino,Maldonado,0,Terciaria completa,Empleado en relación de dependencia,"106.600,00",14500.0,...,No haría nada,Complemento jubilatorio,Prensa especializada,5,7,2,6,3,4,1
143,20093,2026-03-31,53.0,Masculino,Colonia,1,Terciaria completa,Empleado en relación de dependencia,"89.200,00",58100.0,...,No haría nada,Generar una renta mensual,Prensa especializada,7,5,4,6,1,3,2
106,20093,2026-03-31,53.0,Masculino,Colonia,1,Terciaria completa,Empleado en relación de dependencia,"89.200,00",58100.0,...,No haría nada,Generar una renta mensual,Prensa especializada,7,5,4,6,1,3,2
252,20125,03/05/2026,53.0,Femenino,Canelones,0,Terciaria completa,Empleado en relación de dependencia,62600.00,10200.0,...,No haría nada,Generar una renta mensual,Redes sociales,6,7,4,3,2,5,1
8,20125,03/05/2026,53.0,Femenino,Canelones,0,Terciaria completa,Empleado en relación de dependencia,62600.00,10200.0,...,No haría nada,Generar una renta mensual,Redes sociales,6,7,4,3,2,5,1

### Faltantes por columna

                           faltantes
meses_gastos_cubiertos            33
patrimonio_invertible_usd         29
objetivo_principal                27
reaccion_caida_20                 20
ingreso_mensual_liquido           14
edad                               6

### Filas con `meses_gastos_cubiertos` faltante: **33** ### de 657 (se muestran las primeras 3)

,id_cliente,fecha_respuesta,edad,sexo,departamento,cantidad_dependientes,nivel_educativo,ocupacion,ingreso_mensual_liquido,patrimonio_invertible_usd,...,reaccion_caida_20,objetivo_principal,fuente_informacion,prioridad_plazo_fijo,prioridad_letras_bcu,prioridad_fondos_locales,prioridad_obligaciones,prioridad_etf_exterior,prioridad_inmuebles,prioridad_criptomonedas
52,20185,2026-01-09,38.0,Masculino,Maldonado,3,Posgrado,Profesional independiente,S/D,52800.0,...,Vendería todo,Crecimiento del capital,Prensa especializada,6,7,5,3,2,4,1
78,20355,2026-03-03,44.0,Femenino,Montevideo,2,Terciaria completa,Estudiante,24400,2800.0,...,Compraría más,Crecimiento del capital,Banco o corredor de bolsa,6,5,2,4,3,7,1
106,20093,2026-03-31,53.0,Masculino,Colonia,1,Terciaria completa,Empleado en relación de dependencia,"89.200,00",58100.0,...,No haría nada,Generar una renta mensual,Prensa especializada,7,5,4,6,1,3,2

### Filas con `patrimonio_invertible_usd` faltante: **29** ### de 657 (se muestran las primeras 3)

,id_cliente,fecha_respuesta,edad,sexo,departamento,cantidad_dependientes,nivel_educativo,ocupacion,ingreso_mensual_liquido,patrimonio_invertible_usd,...,reaccion_caida_20,objetivo_principal,fuente_informacion,prioridad_plazo_fijo,prioridad_letras_bcu,prioridad_fondos_locales,prioridad_obligaciones,prioridad_etf_exterior,prioridad_inmuebles,prioridad_criptomonedas
15,20550,23/04/2026,58.0,Femenino,MONTEVIDEO,2,Terciaria incompleta,Profesional independiente,0,NaN,...,NaN,Crecimiento del capital,Amigos y familia,7,6,3,4,2,5,1
76,20514,2026-05-13,26.0,Femenino,Montevideo,1,Posgrado,Empresario / dueño de negocio,$ 386.400,NaN,...,Compraría más,Crecimiento del capital,Amigos y familia,7,6,3,4,1,5,2
79,20373,2026-06-13,38.0,Femenino,Maldonado,2,Terciaria incompleta,Empleado en relación de dependencia,"69.300,00",NaN,...,No haría nada,Preservar el capital,Investigación propia,7,6,5,3,2,4,1

### Filas con `objetivo_principal` faltante: **27** ### de 657 (se muestran las primeras 3)

,id_cliente,fecha_respuesta,edad,sexo,departamento,cantidad_dependientes,nivel_educativo,ocupacion,ingreso_mensual_liquido,patrimonio_invertible_usd,...,reaccion_caida_20,objetivo_principal,fuente_informacion,prioridad_plazo_fijo,prioridad_letras_bcu,prioridad_fondos_locales,prioridad_obligaciones,prioridad_etf_exterior,prioridad_inmuebles,prioridad_criptomonedas
60,20283,2026-03-28,38.0,Femenino,Montevideo,0,Terciaria completa,Empleado en relación de dependencia,50300.00,2300.0,...,No haría nada,NaN,Redes sociales,7,6,4,3,2,5,1
122,20290,2026-04-07,48.0,Femenino,Montevideo,2,Terciaria completa,Empleado en relación de dependencia,78300,88900.0,...,No haría nada,NaN,Redes sociales,6,7,3,4,2,5,1
167,20051,07/05/2026,77.0,Masculino,Canelones,2,Terciaria completa,Jubilado,Prefiero no contestar,16800.0,...,No haría nada,NaN,Banco o corredor de bolsa,6,7,4,2,3,5,1

### Filas con `reaccion_caida_20` faltante: **20** ### de 657 (se muestran las primeras 3)

,id_cliente,fecha_respuesta,edad,sexo,departamento,cantidad_dependientes,nivel_educativo,ocupacion,ingreso_mensual_liquido,patrimonio_invertible_usd,...,reaccion_caida_20,objetivo_principal,fuente_informacion,prioridad_plazo_fijo,prioridad_letras_bcu,prioridad_fondos_locales,prioridad_obligaciones,prioridad_etf_exterior,prioridad_inmuebles,prioridad_criptomonedas
15,20550,23/04/2026,58.0,Femenino,MONTEVIDEO,2,Terciaria incompleta,Profesional independiente,0,NaN,...,NaN,Crecimiento del capital,Amigos y familia,7,6,3,4,2,5,1
90,20337,2026-06-14,49.0,Masculino,Montevideo,1,Terciaria incompleta,Jubilado,"50.800,00",3900.0,...,NaN,Crecimiento del capital,Prensa especializada,7,6,4,3,2,5,1
128,20287,2026-04-21,47.0,Masculino,Montevideo,0,Terciaria incompleta,Empleado en relación de dependencia,$ 58.300,3200.0,...,NaN,Generar una renta mensual,Investigación propia,7,6,5,4,2,3,1

### Filas con `ingreso_mensual_liquido` faltante: **14** ### de 657 (se muestran las primeras 3)

,id_cliente,fecha_respuesta,edad,sexo,departamento,cantidad_dependientes,nivel_educativo,ocupacion,ingreso_mensual_liquido,patrimonio_invertible_usd,...,reaccion_caida_20,objetivo_principal,fuente_informacion,prioridad_plazo_fijo,prioridad_letras_bcu,prioridad_fondos_locales,prioridad_obligaciones,prioridad_etf_exterior,prioridad_inmuebles,prioridad_criptomonedas
62,20388,31/05/2026,51.0,Masculino,Montevideo,2,Terciaria completa,Empresario / dueño de negocio,NaN,17200.0,...,No haría nada,Compra de vivienda,Banco o corredor de bolsa,5,6,4,7,2,3,1
196,20399,2026-03-06,44.0,Femenino,Lavalleja,0,Terciaria incompleta,Empleado en relación de dependencia,NaN,5000.0,...,Compraría más,NaN,Investigación propia,5,7,2,4,6,3,1
240,20579,2026-06-08,47.0,Femenino,Tacuarembó,0,Terciaria incompleta,Empleado en relación de dependencia,NaN,2000.0,...,Vendería todo,Preservar el capital,Redes sociales,7,6,5,4,1,3,2

### Filas con `edad` faltante: **6** ### de 657 (se muestran las primeras 3)

,id_cliente,fecha_respuesta,edad,sexo,departamento,cantidad_dependientes,nivel_educativo,ocupacion,ingreso_mensual_liquido,patrimonio_invertible_usd,...,reaccion_caida_20,objetivo_principal,fuente_informacion,prioridad_plazo_fijo,prioridad_letras_bcu,prioridad_fondos_locales,prioridad_obligaciones,prioridad_etf_exterior,prioridad_inmuebles,prioridad_criptomonedas
35,20284,31/05/2026,NaN,Femenino,Montevideo,2,Posgrado,Empleado en relación de dependencia,$ 124.600,0.0,...,No haría nada,Generar una renta mensual,Prensa especializada,6,7,3,5,2,4,1
138,20178,2026-06-15,NaN,Femenino,Salto,0,Terciaria completa,Empleado en relación de dependencia,$ 81.200,NaN,...,No haría nada,Compra de vivienda,Prensa especializada,7,6,4,3,2,5,1
175,20043,2026-03-14,NaN,Femenino,Maldonado,0,Posgrado,Empleado en relación de dependencia,$ 95.300,10300.0,...,Vendería una parte,Educación de los hijos,Redes sociales,7,5,6,3,2,4,1

### **Archivo: movimientos_cartera.csv**

,id_movimiento,id_cliente,id_instrumento,fecha_operacion,tipo_operacion,moneda,monto
0,700954,20141,4,2023-08-06,Compra,UI,17803.22
1,700912,20135,5,2023-11-28,Suscripción,UYU,46255.68
2,700236,20033,3,26/02/2025,Suscripción,UYU,39224.29
3,700992,20148,8,2023-12-09,Suscripción,UYU,195561.19
4,701697,20255,12,17/05/2024,Compra,USD,4324.05

**Filas y columnas:** 4481 filas, 7 columnas

#### Tipos de dato por columna

,id_movimiento,id_cliente,id_instrumento,fecha_operacion,tipo_operacion,moneda,monto
tipo_dato,int64,int64,int64,str,str,str,float64

#### Cantidad de categorías (variables categóricas)

                 cantidad_categorias
fecha_operacion                 1842
tipo_operacion                     2
moneda                             3

#### Descripción estadística (variables continuas)

,count,mean,std,min,25%,50%,75%,max
id_movimiento,4481.0,702241.000000,1293.697608,700001.0,701121.00,702241.00,703361.00,704481.0
id_cliente,4481.0,21328.698728,7713.904545,20001.0,20159.00,20333.00,20490.00,80890.0
id_instrumento,4481.0,6.606115,4.043011,1.0,3.00,7.00,9.00,14.0
monto,4429.0,52325.807589,153294.072601,-718329.5,2138.31,9362.95,39912.73,5317319.6

#### Duplicados exactos: 0 filas

**id_movimiento repetidos:** 0

**Operaciones duplicadas (ignorando id_movimiento):** 94 filas de más (188 filas involucradas)

,id_movimiento,id_cliente,id_instrumento,fecha_operacion,tipo_operacion,moneda,monto
1193,704397,20007,12,2025-09-02,Compra,USD,1733.81
3241,700070,20007,12,2025-09-02,Compra,USD,1733.81
269,700109,20013,14,2025-09-27,Compra,USD,173.64
3494,704429,20013,14,2025-09-27,Compra,USD,173.64
2276,700151,20018,7,2023-06-02,Compra,UI,3114.44
4328,704424,20018,7,2023-06-02,Compra,UI,3114.44
1005,704434,20019,4,2023-05-01,Compra,UI,1414.70
2350,700153,20019,4,2023-05-01,Compra,UI,1414.70
1296,704388,20023,9,2022-10-14,Suscripción,USD,274.53
4337,700186,20023,9,2022-10-14,Suscripción,USD,274.53

### Faltantes por columna

       faltantes
monto         52

### Filas con `monto` faltante: **52** ### de 4481 (se muestran las primeras 3)

,id_movimiento,id_cliente,id_instrumento,fecha_operacion,tipo_operacion,moneda,monto
186,701204,20176,12,2024-10-13,Compra,USD,NaN
218,702999,20454,7,2026-01-13,Suscripción,UI,NaN
383,701964,20301,4,2026-05-08,Compra,UI,NaN

### **Archivo: catalogo_instrumentos.csv**

,id_instrumento,nombre_instrumento,categoria,moneda,inversion_minima,retorno_anual_historico,volatilidad_anual,nivel_riesgo,liquidez
0,1,Plazo fijo en pesos (BROU),Renta fija local,UYU,1000,0.085,0.005,1,Baja
1,2,Plazo fijo en dólares,Renta fija local,USD,500,0.033,0.004,1,Baja
2,3,Letras de Regulación Monetaria (BCU),Renta fija local,UYU,50000,0.092,0.013,1,Media
3,4,Notas del Tesoro en Unidades Indexadas,Renta fija local,UI,30000,0.031,0.026,2,Media
4,5,Fondo de inversión local (AFISA),Fondos,UYU,20000,0.071,0.041,2,Alta

**Filas y columnas:** 14 filas, 9 columnas

#### Tipos de dato por columna

,id_instrumento,nombre_instrumento,categoria,moneda,inversion_minima,retorno_anual_historico,volatilidad_anual,nivel_riesgo,liquidez
tipo_dato,int64,str,str,str,int64,float64,float64,int64,str

#### Cantidad de categorías (variables categóricas)

                    cantidad_categorias
nombre_instrumento                   14
categoria                             9
moneda                                3
liquidez                              4

#### Descripción estadística (variables continuas)

,count,mean,std,min,25%,50%,75%,max
id_instrumento,14.0,7.500000,4.183300,1.0,4.25000,7.5000,10.75000,14.000
inversion_minima,14.0,16550.000000,24805.605756,100.0,625.00000,1750.0000,27500.00000,80000.000
retorno_anual_historico,14.0,0.076214,0.056808,0.0,0.05125,0.0680,0.09025,0.248
volatilidad_anual,14.0,0.111286,0.170478,0.0,0.01625,0.0595,0.12800,0.653
nivel_riesgo,14.0,2.714286,1.437336,1.0,1.25000,3.0000,3.75000,5.000

#### Duplicados exactos: 0 filas

### Faltantes por columna

No hay valores faltantes.

### **Archivo: tasas_referencia.csv**

,concepto,valor,unidad,fecha
0,"Inflación anual Uruguay (IPC, últimos 12 meses)",5.40,%,2026-06-30
1,Meta de inflación del BCU (centro del rango),4.50,%,2026-06-30
2,Tasa de política monetaria del BCU,8.75,%,2026-06-30
3,Tipo de cambio peso / dólar,42.80,UYU por USD,2026-06-30
4,Valor de la Unidad Indexada,6.55,UYU por UI,2026-06-30

**Filas y columnas:** 8 filas, 4 columnas

#### Tipos de dato por columna

          concepto    valor unidad fecha
tipo_dato      str  float64    str   str

#### Cantidad de categorías (variables categóricas)

          cantidad_categorias
concepto                    8
unidad                      3
fecha                       1

#### Descripción estadística (variables continuas)

       count  mean        std  min  25%    50%     75%   max
valor    8.0  10.5  13.242006  2.7  4.4  5.975  8.8625  42.8

#### Duplicados exactos: 0 filas

### Faltantes por columna

No hay valores faltantes.